name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  release:
    name: "Release"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Maven Settings
      uses: s4u/maven-settings-action@v3.0.0

    - name: Build with Maven
      run: mvn clean verify

    - name: Package with Maven
      run: mvn package -DskipTests

    - name: Publish to GitHub Packages
      run: mvn deploy
      env:
        GITHUB_USERNAME: ${{ secrets.GITHUB_ACTOR }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Release notes for ${{ github.ref }}.
        draft: false
        prerelease: false
