name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [21, 25]
        profile: [java21, java25]
        include:
          - java: 21
            profile: java21
          - java: 25
            profile: java25

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Setup Maven Settings
        uses: s4u/maven-settings-action@v4.0.0
        with:
          servers: '[{"id": "central", "username": "${{secrets.MAVEN_USERNAME}}", "password": "${{secrets.MAVEN_PASSWORD}}"}]'

      - name: Extract version from tag
        id: extract_version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean verify -P${{ matrix.profile }} -Dmaven.test.useModulePath=false
        working-directory: location4j
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Package with Maven
        if: matrix.java == 21
        run: mvn versions:set -DnewVersion=${{ env.RELEASE_VERSION }} && mvn package -DskipTests
        working-directory: location4j

      - name: Deploy Github and Maven Central
        if: matrix.java == 21
        run: mvn deploy
        working-directory: location4j
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
